-- LW VEÍCULOS — SECURITY HARDENING V1
-- Execute uma vez no Supabase SQL Editor.
-- IMPORTANTE: este script preserva o estoque existente.

-- 1) Soft delete
alter table public.vehicles add column if not exists deleted_at timestamptz;

-- 2) Auditoria
create table if not exists public.admin_audit_log(
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete restrict,
  action text not null check (char_length(action) between 2 and 80),
  vehicle_id uuid references public.vehicles(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.admin_audit_log enable row level security;

drop policy if exists "admins read audit" on public.admin_audit_log;
create policy "admins read audit" on public.admin_audit_log
for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins write audit" on public.admin_audit_log;
create policy "admins write audit" on public.admin_audit_log
for insert to authenticated
with check (
  user_id=auth.uid()
  and exists(select 1 from public.admins a where a.user_id=auth.uid())
);

-- 3) Público só enxerga anúncios públicos e não apagados.
drop policy if exists "public read vehicles" on public.vehicles;
drop policy if exists "public read published vehicles" on public.vehicles;
create policy "public read published vehicles" on public.vehicles
for select to anon
using (status in ('available','sold') and deleted_at is null);

-- Admin autenticado pode ler inclusive rascunhos e lixeira.
drop policy if exists "admins read all vehicles" on public.vehicles;
create policy "admins read all vehicles" on public.vehicles
for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- 4) Imagens: público só lê metadados de veículos públicos.
drop policy if exists "public read vehicle images" on public.vehicle_images;
drop policy if exists "public read published vehicle images" on public.vehicle_images;
create policy "public read published vehicle images" on public.vehicle_images
for select to anon
using (exists(
  select 1 from public.vehicles v
  where v.id=vehicle_images.vehicle_id
    and v.status in ('available','sold')
    and v.deleted_at is null
));

drop policy if exists "admins read all vehicle images" on public.vehicle_images;
create policy "admins read all vehicle images" on public.vehicle_images
for select to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- 5) Faltavam UPDATE/DELETE de imagens na configuração original.
drop policy if exists "admins update vehicle images" on public.vehicle_images;
create policy "admins update vehicle images" on public.vehicle_images
for update to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins delete vehicle images" on public.vehicle_images;
create policy "admins delete vehicle images" on public.vehicle_images
for delete to authenticated
using (exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- 6) Storage: upload somente por admin, pasta obrigatoriamente começa com UUID do veículo.
drop policy if exists "admins upload vehicle storage" on storage.objects;
create policy "admins upload vehicle storage" on storage.objects
for insert to authenticated
with check(
  bucket_id='vehicle-images'
  and exists(select 1 from public.admins a where a.user_id=auth.uid())
  and (storage.foldername(name))[1] is not null
);

drop policy if exists "admins update vehicle storage" on storage.objects;
create policy "admins update vehicle storage" on storage.objects
for update to authenticated
using(bucket_id='vehicle-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()))
with check(bucket_id='vehicle-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

drop policy if exists "admins delete vehicle storage" on storage.objects;
create policy "admins delete vehicle storage" on storage.objects
for delete to authenticated
using(bucket_id='vehicle-images' and exists(select 1 from public.admins a where a.user_id=auth.uid()));

-- 7) Índices úteis
create index if not exists vehicles_public_idx on public.vehicles(status,deleted_at,created_at desc);
create index if not exists audit_created_idx on public.admin_audit_log(created_at desc);
